config/routes.rb
Portfolio::Application.routes.draw do
  resources :projects

  root :to => "home#index"
  match  '/about', to: 'home#about', via: 'get'

end

app/models/project.rb
class Project < ActiveRecord::Base
	has_attached_file :thumb

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  	@projects = Project.all
  	@categories = Project.uniq.pluck(:work)
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render action: 'show', status: :created, location: @project }
      else
        format.html { render action: 'new' }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:name, :description, :work, :content, :thumb)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/home/about.html.erb
<section id="page-title" class="container">

		<div class="row">
			<div class="span10">
				<h2>About</h2>
			</div>
		</div>
		<div class="row">
			<hr class="span12 clear-bottom">
		</div>
	</section>
	<!-- End Title -->

	<section class="container">
		<div class="row">
			<div class="span4">
				<img src="/about.jpg" />
			</div>
			<div class="span8">
				<h5>I'm a flexible, active freelancer and through my passion for design, I craft simple and functional websites and mobile apps. I'm committed and enthusiastic about every project I take on and I simply love designing. <br /><br />
				<span class="about-text">I use research, strategy, and problem solving to take your ideas and work with you to make them even better.</span> <br /> <br />
				I bring your project to life with clean and standards-based code using the latest techniques and technologies. I ensure that your business and user goals remain a mantra through the lifecycle of your project up to launch and beyond.<br /> <br />
				</h5>
					<div class="vertical-align">
						<a class="presentation" href="/anggi-resume.pdf">
								<i class="icon-file"></i>
							<div class="pdf-desc">
								<p class="pdf-title">Download <span class="visible-big-desktop">Resume</span></p>
								<p class="pdf-info">PDF file, 123 Kb</p>
							</div>
						</a>
					</div>
			</div>
		</div>
	</div>

app/views/home/index.html.erb
  <section id="page-title" class="container">
    <div class="row">
      <div class="span10">
        <h2>Portfolio</h2>
        <div class="dropdown">
            <div class="dropmenu">
              <p class="menu-title">Show</p>
              <p class="selected">All projects</p>
              <i class="icon-chevron-down"></i>
            </div>
            <div class="dropmenu-active">
              <ul class="option-set" data-option-key="filter">
                <li><a class="selected drop-selected" href="#filter" data-option-value="*">All projects</a></li>
                 <% @categories.each do |work| %>
                <li><a href="#filter" data-option-value=".<%= work %>"><%= work.capitalize %></a></li>
                <% end %>
              </ul>
            </div>
          </div>
      </div>
    </div>
    <div class="row">
      <hr class="span12 clear-bottom">
    </div>
  </section>

    <section id="projects" class="container">
    <div id="posts" class="isotope row">
    
      <!-- Start Project -->

      <% @projects.each do |project| %>
      <div class="post item span4 isotope-item <%= project.work %>">
          <a href="<%= url_for(project) %>" class="project-wrp hover-down">
            <div class="content-wrp">
                <%= image_tag project.thumb.url %>
                <p class="project-name"><%= project.name %></p>
                <p class="project-desc"><%= project.description %></p>
            </div>
            <div class="overlay-wrp">
                <div class="overlay"></div>
            <p class="project-name"><%= project.name %></p>
            <p class="project-desc"><%= project.description %></p>
            <i class="icon-arrow-right"></i>
              </div>
          </a>
      </div>
      <% end %>
      <!-- End Project -->
      
    </div>  
  </section>

  <section class="container">
    <div class="row">
      <div class="span12">
        <div class="info-block">
          <div class="ib-text">
            <h6>Fork me on Github</h6>
            <p>This portfolio is built on Ruby on Rails and available as open-source. Feel free to fork this project on github and use it as your own.</p>
            <a href="#" class="btn rounded color">Download</a>
            <br />
          </div>
        </div>
      </div>
    </div>
  </section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Anggi Priatmadi Portfolio</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

	<section id="title" class="container">
		<div class="row">
			<div class="span12">
				<a href="/"><h3><span class="color-text">Anggi</span> Priatmadi</h3></a>
				<div class="date"><%= link_to "Home", root_path %> • <%= link_to "About", about_path %></div>
			</div>
		</div>
	</section>

	<section class="intro container">
	    <div class="row">
	      <div class="span12">
	        <p>Simple and functional design for the web and mobile
	        <br />
	        <a class="email" href="#">Send me an email</a></p>
	      </div>
	    </div>
	  </section>

<%= yield %>

	<!-- Start Footer -->
	<footer class="container">
		<div class="row">
			<div class="span12">
				Copyright 2013 | Anggi Priatmadi
			</div>
		</div>
	</footer>
	<!-- End Footer -->


</body>
</html>

app/views/projects/_form.html.erb
<%= form_for @project, :html => { :multipart => true } do |f| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% @project.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :work %><br />
    <%= f.text_field :work %>
  </div>
  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_area :content %>
  </div>
  <div class="field">
    <%= f.file_field :thumb %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/projects/edit.html.erb
<h1>Editing project</h1>

<%= render 'form' %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<h1>Listing projects</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Work</th>
      <th>Content</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @projects.each do |project| %>
    <tr>
      <td><%= project.name %></td>
      <td><%= project.description %></td>
      <td><%= project.work %></td>
      <td><%= project.content %></td>
      <td><%= link_to 'Show', project %></td>
      <td><%= link_to 'Edit', edit_project_path(project) %></td>
      <td><%= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
    <% end %>
  </tbody>
</table>

<br />

<%= link_to 'New Project', new_project_path %>

app/views/projects/new.html.erb
<h1>New project</h1>

<%= render 'form' %>

<%= link_to 'Back', projects_path %>

app/views/projects/show.html.erb
<p id="notice"><%= notice %></p>

	<section class="container project-title">
		<div class="row">
			<div class="span12">
				<h1><%= @project.name %></h1>
				<div class="sub-title"><%= @project.description %></div>
			</div>
			<p class="span10 offset1 portfolio-text">
				<%= @project.content.html_safe %>
			</p>
		</div>
	</section>